# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Ensure that yak_filesystem_configuration.volume_type is valid
  ansible.builtin.assert:
    that: 
      yak_filesystem_configuration.volume_type == 'standard'
      or
      yak_filesystem_configuration.volume_type == 'gp2'
      or
      yak_filesystem_configuration.volume_type == 'gp3'
      or
      yak_filesystem_configuration.volume_type == 'io1'
      or
      yak_filesystem_configuration.volume_type == 'io2'
      or
      yak_filesystem_configuration.volume_type == 'sc1'
      or
      yak_filesystem_configuration.volume_type == 'st1'
    fail_msg: "'yak_filesystem_configuration.volume_type' has an invalid value. Please use 'standard', 'gp2', 'gp3', 'io1', 'io2', 'sc1' or 'st1'."
    success_msg: "'yak_filesystem_configuration.volume_type' has a valid value."

...