# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Get instance info to find ID
  include_tasks: get_ec2_instance_info.yml

- debug: var=r_ec2_instance_info
  delegate_to: localhost
  when: debug|bool

- name: Terminate instances that were previously retrieved
  delegate_to: localhost
  amazon.aws.ec2_instance:
    state: absent
    region: "{{ region_id }}"
    instance_ids: '{{ r_ec2_instance_info.instances[0].instance_id }}'
    wait: yes
    wait_timeout: 600
  when: r_ec2_instance_info.instances|length > 0

- name: Delete key from ssh config file
  delegate_to: localhost
  blockinfile:
    path: "{{ yak_local_ssh_config_file }}"
    state: absent
    marker: "## {mark} ANSIBLE MANAGED BLOCK - {{ inventory_hostname }} ##"
  failed_when: false

- name: Delete server key pair
  delegate_to: localhost
  amazon.aws.ec2_key:
    region: "{{ region_id }}"
    name: "{{ machine_name }}"
    state: absent
  failed_when: false
