- block:
  - name: Get the current caller identity - Verifying credentials are valid
    delegate_to: localhost
    amazon.aws.aws_caller_info:
    environment:
      AWS_ACCESS_KEY_ID     : "{{ yak_aws_ec2_aws_access_key_id }}"
      AWS_SECRET_ACCESS_KEY : "{{ yak_aws_ec2_aws_secret_access_key }}"
      AWS_SESSION_TOKEN     : "{{ yak_aws_ec2_aws_session_token }}"
    retries: 3
    delay: 5
  rescue:
  - fail:
      msg: 'Please ensure your AWS credentials are valid.'
