# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3

- name: Insert/Update ssh config file
  delegate_to: localhost
  blockinfile:
    path: "{{ yak_local_ssh_config_file }}"
    create: true
    mode: 0600
    marker: "## {mark} ANSIBLE MANAGED BLOCK - {{ inventory_hostname }} ##"
    block: |
      Host {{ administrative_ip }} {{ inventory_hostname }}
          HostName {{ administrative_ip }}
          Port {{ ansible_port|default(22) }}
          User {{ ansible_user }}
          StrictHostKeyChecking no
          IdentityFile {{ ansible_ssh_private_key_file }}
          ServerAliveInterval 60

