# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
- name: Get instance info to find ID
  include_tasks: get_ec2_instance_info.yml
  apply:
    until: host_ip_access == 'private_ip' or (r_ec2_instance_info.instances[0].public_ip_address is defined and r_ec2_instance_info.instances[0].public_ip_address != "") 
    retries: 12
    delay: 10

- debug: var=r_ec2_instance_info
  when: debug | bool

- name: Update yak inventory
  delegate_to: localhost
  yak.core.yak_inventory_update:
    server_name: "{{ inventory_hostname }}"
    private_ip: "{{ r_ec2_instance_info.instances[0].private_ip_address |default(None) }}"
    public_ip: "{{ r_ec2_instance_info.instances[0].public_ip_address |default(None) }}"

- name: Refresh inventory to ensure IPs are up to date
  ansible.builtin.meta: refresh_inventory

- include_tasks: "post_config_{{ os_type }}.yml"

- include_tasks: "wait_for_connection_{{ os_type }}.yml"

- name: Update server state
  delegate_to: localhost
  yak.core.yak_inventory_update:
    server_name: "{{ target }}"
    server_state: running
  when: yak_inventory_type == "database"

- set_fact:
    administrative_ip: "{{ r_ec2_instance_info.instances[0].private_ip_address }}"
  when: host_ip_access == 'private_ip'

- set_fact:
    administrative_ip: "{{ r_ec2_instance_info.instances[0].public_ip_address }}"
  when: host_ip_access == 'public_ip'

- name: Return facts to playbook
  delegate_to: localhost
  set_fact:
    returned:
      instance: "{{ r_ec2_instance_info.instances[0] }}"
      administrative_ip: "{{ administrative_ip }}"
      private_ip_address: "{{ r_ec2_instance_info.instances[0].private_ip_address|default(None) }}"
      public_ip_address: "{{ r_ec2_instance_info.instances[0].public_ip_address|default(None) }}"

- include_tasks: "update_detail_file.yml"








