# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Wait for connection to the server
  ansible.builtin.wait_for_connection:

- name: Ensure ansible user password doesn't expire
  ansible.windows.win_user:
    name: '{{ ansible_user }}'
    password_never_expires: true
