# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
- include_tasks: get_number_of_instances.yml
- block:
  - include_tasks: set_key_if_not_exists.yml
  - include_tasks: derive_image_id.yml
  - include_tasks: "create_{{ os_type }}.yml"
  - include_tasks: post_config_{{ os_type }}.yml
  when: number_of_instances | int == 0

- when: number_of_instances | int > 0
  block:
    - debug:
        msg: "The instance already exists. Skipping instance creation..."

    - name: Start EC2 instance if not already started
      delegate_to: localhost
      amazon.aws.ec2_instance:
        region: "{{ region_id }}"
        state: started
        instance_ids:
          - "{{ r_ec2_instance_info.instances[0].instance_id }}"