# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Create a new ec2 key pair
  delegate_to: localhost
  amazon.aws.ec2_key:
    region: "{{ region_id }}"
    name: "{{ machine_name }}"
    key_material: "{{ lookup('file', ansible_ssh_public_key_file) }}"
  register: r_ec2_key

