---
- name: Creates yak directory if needed
  delegate_to: localhost
  ansible.builtin.file:
    path: ~/yak/configuration/infrastructure/.yak
    state: directory

- name: Creating the instance file with instance details
  delegate_to: localhost
  no_log: True
  ansible.builtin.lineinfile:
    path: "~/yak/configuration/infrastructure/.yak/server.{{ target|replace('/','.') }}"
    regexp: '^{{ item.key }}'
    line: '{{ item.key }}: "{{ item.value }}"'
    create: true
  loop: '{{ returned_instance_configuration | dict2items }}'
