argument_specs:
  main:
    short_description: The main entry point for the linux_name_resolution role
    options:
      dns_records:
        type: "list"
        required: false
        elements: "dict"
        description: "Lists of dicts that represent dns records"
        options:
          domain_name:
            type: "str"
            required: true
            description: "Domain name, e.g. example.com"
          aliases:
            type: "list"
            required: true
            elements: "dict"
            description: "List of dicts that contains the aliases to define for given domain"
            options:
              name: 
                type: "str"
                required: true
                description: "Hostname of machine, without domain, e.g. k8s-master"
              ip_addresses:
                type: "list"
                required: false
                elements: "str"
                description: "List of IP addresses that must match the FQDN"
              yak_inventory_hostnames:
                type: "list"
                required: false
                elements: "str"
                description: "Define yak inventory hostname that must match with FQDN. IP will be automatically determined."