# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---

- debug:
    msg: '{{ yak_inventory_os_storages }}'

- when : provider != "on_premises"
  include_tasks: os_storage_setup.yml
  loop: '{{ yak_inventory_os_storages }}'
  loop_control:
    loop_var: 'yak_filesystem_configuration'