- name: Ensure configuration file exists
  delegate_to: localhost
  ansible.builtin.file:
    path: "~/.oci/config"
    state: touch
    mode: '0600'
  become: true

- block:
    - name: Check credentials by listing api key fact
      delegate_to: localhost
      oracle.oci.oci_identity_api_key_facts:
        # required
        user_id: "{{ yak_oci_compute_oci_user_id }}"
        api_user: "{{ yak_oci_compute_oci_user_id }}"
        auth_type: "{{ yak_oci_compute_oci_ansible_auth_type }}"
        api_user_fingerprint: "{{ yak_oci_compute_oci_user_fingerprint }}"
        api_user_key_file: "{{ yak_oci_compute_oci_user_key_file }}"
        region: "{{ yak_oci_compute_oci_region }}"
        tenancy: "{{ yak_oci_compute_oci_tenancy }}"
      retries: 3
      delay: 5
      no_log: true
  rescue:
    - fail:
        msg: 'Please ensure your OCI credentials are valid.'
