- name: Ensure configuration file exists
  delegate_to: localhost
  ansible.builtin.file:
    path: "~/.oci/config"
    state: touch
    mode: '0600'
  become: true

- block:
    - name: Check credentials by listing api key fact
      delegate_to: localhost
      oracle.oci.oci_identity_api_key_facts:
        # required
        user_id: "{{ lookup('env','OCI_USER_ID') }}"
        auth_type: "{{ lookup('env','OCI_ANSIBLE_AUTH_TYPE',default='api_key') }}"
        api_user_fingerprint: "{{ lookup('env','OCI_USER_FINGERPRINT') }}"
        api_user_key_file: "{{ lookup('env','OCI_USER_KEY_FILE') }}"
        region: "{{ lookup('env','OCI_REGION') }}"
      retries: 3
      delay: 5
      no_log: true
  rescue:
    - fail:
        msg: 'Please ensure your AWS credentials are valid.'

