# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- include_tasks: create_vnic_details.yml

- name: Call the role to generate the Linux init script
  include_role:
    name: yak.core.linux_init_script

  # https://cloudinit.readthedocs.io/en/latest/explanation/format.html
- name: Format Linux script to cloud init format
  set_fact:
    cloud_init_script: |
      #!/bin/sh
      {{ linux_init_script }}

- name: Create instance
  delegate_to: localhost
  oracle.oci.oci_compute_instance:
    state: present
    region: "{{ region }}"
    availability_domain: "{{ availability_domain }}"
    compartment_id: "{{ compartment_id }}"
    shape: "{{ shape.name }}"
    shape_config:
      memory_in_gbs: "{{ shape.memory_in_gbs }}"
      ocpus: "{{ shape.ocpus }}"
    image_id: "{{ image_id }}"
    display_name: "{{ display_name }}"
    subnet_id: "{{ subnet_id }}"
    create_vnic_details: "{{ vnic_details }}"
    source_details:
      boot_volume_size_in_gbs: "{{ role_root_oci_boot_volume_options.boot_volume_size_in_gbs }}"
      boot_volume_vpus_per_gb: "{{ role_root_oci_boot_volume_options.boot_volume_vpus_per_gb }}"
      source_type: "image"
      image_id: "{{ image_id }}"
    preserve_boot_volume: "{{ not role_root_oci_boot_volume_options.delete_on_termination }}"
    is_pv_encryption_in_transit_enabled: "{{ role_root_oci_boot_volume_options.is_pv_encryption_in_transit_enabled }}"
    metadata : { "ssh_authorized_keys": "{{ lookup('file', ansible_ssh_public_key_file) }}", "user_data": "{{ cloud_init_script | b64encode }}" }
    freeform_tags: "{{ custom_tags }}"
  register: r_oci_compute_instance_present

- debug: var=r_oci_compute_instance_present
  delegate_to: localhost
  when: debug | bool
