# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- include_tasks: post_config.yml

- name: Update yak inventory
  delegate_to: localhost
  yak.core.yak_inventory_update:
    server_name: "{{ inventory_hostname }}"
    private_ip: "{{ oci_private_ip|default(None) }}"
    public_ip: "{{ oci_public_ip|default(None) }}"

- name: Refresh inventory to ensure IPs are up to date
  ansible.builtin.meta: refresh_inventory

- name: Wait for the OS to be reachable by YaK
  ansible.builtin.wait_for_connection:
    delay: 60
    timeout: 600

- name: Update server state
  delegate_to: localhost
  yak.core.yak_inventory_update:
    server_name: "{{ target }}"
    server_state: running
  when: yak_inventory_type == "database"

- name: Return facts to playbook
  delegate_to: localhost
  no_log: True
  set_fact:
    returned:
      instance: "{{ r_oci_compute_instance_facts.instances[0] }}"
      administrative_ip: "{{ administrative_ip|default('none')  }}"
      private_ip_address: "{{ oci_private_ip|default('none')  }}"
      public_ip_address: "{{ oci_public_ip|default('none') }}"
      os_admin_username: "{{ ansible_user|default('none') }}"
      os_admin_password: "{{ os_admin_password|default('none') }}"

- include_tasks: "update_detail_file.yml"
