# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Get OCI instances facts
  delegate_to: localhost
  oracle.oci.oci_compute_instance_facts:
    compartment_id: "{{ compartment_id }}"
    display_name: "{{ display_name }}"
    lifecycle_state: RUNNING
  register: r_oci_compute_instance_facts

- debug: var=r_oci_compute_instance_facts
  when: debug|bool

- name: Fail is expected number of instance is not OK
  ansible.builtin.fail:
    msg: There are no or more than 1 instance in RUNNING state with the name '{{ display_name }}'.
  when: r_oci_compute_instance_facts.instances|length != 1

# TODO Test if it doesnt fail when no public ip.
- set_fact:
    oci_private_ip: "{{ r_oci_compute_instance_facts.instances[0].primary_private_ip }}"
    oci_public_ip: "{{ r_oci_compute_instance_facts.instances[0].primary_public_ip }}"

- set_fact:
    administrative_ip: "{{ oci_private_ip }}"
  when: host_ip_access == 'private_ip'

- set_fact:
    administrative_ip: "{{ oci_public_ip }}"
  when: host_ip_access == 'public_ip'

- name: Update yak inventory
  delegate_to: localhost
  yak.core.yak_inventory_update:
    server_name: "{{ inventory_hostname }}"
    private_ip: "{{ oci_private_ip|default(None) }}"
    public_ip: "{{ oci_public_ip|default(None) }}"

- name: Refresh inventory to ensure IPs are up to date
  ansible.builtin.meta: refresh_inventory

- include_tasks: post_config_{{ os_type }}.yml

- name: Wait for SSH to come up
  wait_for_connection:

- name: Update server state
  delegate_to: localhost
  yak.core.yak_inventory_update:
    server_name: "{{ target }}"
    server_state: running
  when: yak_inventory_type == "database"

- name: Prepare Return facts to playbook
  delegate_to: localhost
  block:
    - set_fact:
        _returned_instance_configuration:
          administrative_ip: "{{ administrative_ip }}"
          private_ip_address: "{{ oci_private_ip }}"
          public_ip_address: "{{ oci_public_ip|default('none') }}"
      no_log: true

    - set_fact:
        returned_instance_configuration: '{{ returned_instance_configuration|default({}) | ansible.builtin.combine(_returned_instance_configuration, recursive=true) }}'
      no_log: true

- include_tasks: "update_detail_file.yml"




