# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Get OCI instances facts
  delegate_to: localhost
  oracle.oci.oci_compute_instance_facts:
    compartment_id: "{{ compartment_id }}"
    display_name: "{{ display_name }}"
    lifecycle_state: RUNNING
  register: r_oci_compute_instance_facts

- debug: var=r_oci_compute_instance_facts
  when: debug|bool

- name: Fail is expected number of instance is not OK
  ansible.builtin.fail:
    msg: There are no or more than 1 instance in RUNNING state with the name '{{ display_name }}'.
  when: r_oci_compute_instance_facts.instances|length != 1

- set_fact:
    oci_private_ip: "{{ r_oci_compute_instance_facts.instances[0].primary_private_ip }}"
    oci_public_ip: "{{ r_oci_compute_instance_facts.instances[0].primary_public_ip }}"

- set_fact:
    administrative_ip: "{{ oci_private_ip }}"
  when: host_ip_access == 'private_ip'

- set_fact:
    administrative_ip: "{{ oci_public_ip }}"
  when: host_ip_access == 'public_ip'
