# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
- include_tasks: checks.yml

- block:
    - include_tasks: create_{{ os_type }}.yml
    - include_tasks: post_config_{{ os_type }}.yml
  when: filtered_instance_id|length == 0

- when: filtered_instance_id|length > 0
  block:
    - fail:
        msg: "Cannot Deploy as the instance already exists."
  always:
    - name: Update server state
      delegate_to: localhost
      yak.core.yak_inventory_update:
        server_name: "{{ target }}"
        server_state: stopped
      when: yak_inventory_type == "database"