---
- name: Creates yak directory if needed
  delegate_to: localhost
  ansible.builtin.file:
    path: ~/yak/configuration/infrastructure/.yak
    state: directory

- name: Creating the instance file with instance details
  delegate_to: localhost
  no_log: True
  ansible.builtin.copy:
    dest: "~/yak/configuration/infrastructure/.yak/server.{{ target|replace('/','.') }}"
    content: |
      administrative_ip: "{{ returned_instance_configuration.administrative_ip|default('none')  }}"
      private_ip_address: "{{ returned_instance_configuration.private_ip_address|default('none')  }}"
      public_ip_address: "{{ returned_instance_configuration.public_ip_address|default('none') }}"
      os_admin_username: "{{ returned_instance_configuration.os_admin_username|default('none') }}"
      os_admin_password: "{{ returned_instance_configuration.os_admin_password|default('none') }}"
...