# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
# plugin: yak.core.file

#
# Custom configuration
#

# debug: to display debugging information in
# stdout for troubleshooting purpose.
# Environment variable: DEBUG
debug: false

# windows_ansible_user: Default user for windows
# Created a instance creation and used as Ansible user
windows_ansible_user: Ansible

# default_server_os_type: Define the default os_type value when not defined
# choices: ["linux", "windows"]
default_server_os_type: linux
