# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
- name: Gather information about instance
  delegate_to: localhost
  community.aws.ec2_instance_info:
    region: "{{ region_id }}"
    filters:
      "tag:Name": "{{ machine_name }}"
      instance-state-name: [ "pending", "running", "shutting-down", "stopping", "stopped" ]
  register: r_ec2_instance_info

- name: Get volume(s) info from EC2 Instance
  delegate_to: localhost
  amazon.aws.ec2_vol_info:
    region: "{{ region_id }}"
    filters:
      attachment.instance-id: "{{ r_ec2_instance_info.instances[0].instance_id }}"
      "tag:Name": disk*
  register: r_attached_volumes

- name: Re-collect facts after disk addition and ensure expected data is present
  community.windows.win_disk_facts:

- debug: var=r_attached_volumes
  when: debug|bool

- debug: var=ansible_disks
  when: debug|bool

- name: Derive the pv list
  delegate_to: localhost
  yak.core.derive_pv_list:
    provider: "{{ provider }}"
    os_type: "{{ os_type }}"
    vol_info: "{{ r_attached_volumes }}"
    ansible_disks: "{{ ansible_disks }}"
  register: r_derive_pv_list

- set_fact:
    pv_list_extended: "{{ r_derive_pv_list.pv_list_extended }}"

- debug: var=pv_list_extended
  when: debug | bool
