# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- set_fact:
    iscsi_commands: "{{ r_oci_blockstorage_volume_attachment.volume_attachment.iscsi_attach_commands }}"

- name: Run ISCSI configuration
  ansible.windows.win_powershell:
    script: "{{ iscsi_commands|join('\n') }}"

- name: Get disk number per TargetNodeAddress
  ansible.windows.win_powershell:
    script: |
      # Take each disk number and get drive letter and iSCSI conenctions from variables
      Foreach ($disk in Get-Disk| ?{$_.BusType -Eq "iSCSI"}) {
          $ISCSI = Get-Disk -Number $disk.Number | Get-IscsiSession

        # Custom Output based on variables
          [pscustomobject]@{
              DiskNumber=$disk.Number -join '';
              TargetNodeAddress=$ISCSI.TargetNodeAddress -join '';

          }
      }
  register: r_disk_number_per_target_node_address

# The next task expects this format.
- set_fact:
    pv_list_extended: >
      {{
        [
          {
            'drive_letter': yak_filesystem_configuration.drive_letter,
            'partition_label': yak_filesystem_configuration.partition_label,
            'windows_disk_number': r_disk_number_per_target_node_address|json_query('output[?TargetNodeAddress==`'+r_oci_blockstorage_volume_attachment.volume_attachment.iqn|string+'`].DiskNumber|[0]')|int
          }
        ]
      }}

- debug: var=pv_list_extended
  when: debug | bool
