# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
- name: Get azure_rm_virtualmachine_info
  delegate_to: localhost
  azure_rm_virtualmachine_info:
    name: "{{ machine_name }}"
    resource_group: "{{ resource_group }}"
  register: r_azure_rm_virtualmachine_info

- debug: var=r_azure_rm_virtualmachine_info
  when: debug|bool

- name: Get azure_rm_manageddisk_info
  delegate_to: localhost
  azure.azcollection.azure_rm_manageddisk_info:
    managed_by: "{{ r_azure_rm_virtualmachine_info.vms[0].id }}"
  register: r_azure_rm_manageddisk_info

- debug: var=r_azure_rm_manageddisk_info
  when: debug|bool

- name: Get disk facts
  win_disk_facts:

- debug: var=ansible_disks
  when: debug|bool

- name: Derive the pv list
  delegate_to: localhost
  yak.core.derive_pv_list:
    provider: "{{ provider }}"
    os_type: "{{ os_type }}"
    azure_rm_virtualmachine_info: "{{ r_azure_rm_virtualmachine_info }}"
    azure_rm_manageddisk_info: "{{ r_azure_rm_manageddisk_info }}"
    ansible_disks: "{{ ansible_disks }}"
  register: r_derive_pv_list

- when: item.drive_letter == yak_filesystem_configuration.drive_letter
  set_fact:
    pv_list_extended: ['{{ item }}']
  loop: '{{ r_derive_pv_list.pv_list_extended }}'

- debug: var=pv_list_extended
  when: debug | bool
