# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Initialize a disk
  community.windows.win_initialize_disk:
    disk_number: "{{ item.windows_disk_number }}"
  loop: "{{ pv_list_extended }}"

- name: Create partitions with max size
  community.windows.win_partition:
    drive_letter: "{{ item.drive_letter }}"
    partition_size: -1
    disk_number: "{{ item.windows_disk_number }}"
  loop: "{{ pv_list_extended }}"

- name: Format to NTFS partitions that have no filesystem
  community.windows.win_format:
    drive_letter: "{{ item.drive_letter }}"
    file_system: NTFS
    new_label: "{{ item.partition_label }}"
    full: no
  loop: "{{ pv_list_extended }}"
