# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- set_fact:
    ssh_port: "{{ ansible_port|default(22) }}"

- name: Generate the Linux init script
  set_fact:
    linux_init_script: |
      exec >>/tmp/set_ssh_port.log 2>&1
      echo "BEGIN"
      set -x
      if [ "{{ ssh_port }}" != "22" ]; then

        # Derive OS family
        if [ $(egrep -c '^ID_LIKE=' /etc/os-release) -eq 1 ]; then
          OS_FAMILY="$(cat /etc/os-release |egrep '^ID_LIKE=' |awk -F '=' '{print $2}' | sed 's/"//g')"
        else
          OS_FAMILY="$(cat /etc/os-release |egrep '^ID=' |awk -F '=' '{print $2}' | sed 's/"//g')"
        fi

        # Change Port number in SSH configuration
        cp /etc/ssh/sshd_config /etc/ssh/sshd_config.ori
        sed -E 's/^[# ]*Port[ ]*[0-9]+/Port {{ ssh_port }} # Changed by YaK /g' /etc/ssh/sshd_config.ori > /etc/ssh/sshd_config

        # Firewall open/close new/old SSH port
        if [ "$(which firewall-cmd|wc -l)" == "1" ]; then
          firewall-offline-cmd --add-port {{ ssh_port }}/tcp
          firewall-offline-cmd --remove-service=ssh
          firewall-offline-cmd --enabled
          systemctl restart firewalld
        fi
        if [ "$(which ufw|wc -l)" == "1" ]; then
          ufw allow {{ ssh_port }}/tcp
          ufw delete allow ssh
        fi

        # Adjust SE Linux
        if [ "$(/usr/sbin/sestatus | grep 'SELinux status' | awk '{print $3}')" == "enabled" ]; then
          yum install -y policycoreutils
          semanage port -a -t ssh_port_t -p tcp {{ ssh_port }}
          semanage port -m -t ssh_port_t -p tcp {{ ssh_port }}
        fi

        case "${OS_FAMILY}" in
          debian)
              systemctl restart sshd.service
            ;;
          fedora)
              systemctl restart sshd.service
            ;;
          *)
              systemctl restart sshd.service
            ;;
        esac
      fi
      echo "END"

- debug: var=linux_init_script
  when: debug|bool
