# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Delete the VM
  delegate_to: localhost
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ server_name }}"
    remove_on_absent: all
    state: absent
  register: r_azure

- debug: var=r_azure
  delegate_to: localhost
  when: debug | bool

- name: Remove the public IP if any
  delegate_to: localhost
  azure.azcollection.azure_rm_publicipaddress:
    resource_group: "{{ resource_group }}"
    name: "{{ server_name }}-public-ip-01"
    state: absent

- name: Delete key from ssh config file
  delegate_to: localhost
  blockinfile:
    path: "{{ yak_local_ssh_config_file }}"
    state: absent
    marker: "## {mark} ANSIBLE MANAGED BLOCK - {{ inventory_hostname }} ##"
