- block:
    - name: Check credentials by fetching subscription info
      delegate_to: localhost
      azure.azcollection.azure_rm_subscription_info:
      retries: 3
      delay: 5
      no_log: true

  rescue:
    - fail:
        msg: 'Please ensure your AWS credentials are valid.'
