- name: Get VM by name
  delegate_to: localhost
  azure.azcollection.azure_rm_virtualmachine_info:
    resource_group: "{{ resource_group }}"
  register: r_get_vm_state

- name: Get facts for current logged in user
  delegate_to: localhost
  azure.azcollection.azure_rm_account_info: