- block:
    - name: Check credentials by fetching subscription info
      delegate_to: localhost
      azure.azcollection.azure_rm_subscription_info:
      retries: 3
      delay: 5
      no_log: true
      environment:
        AZURE_SUBSCRIPTION_ID: '{{ yak_azure_virtualmachine_azure_subscription_id }}'
        AZURE_CLIENT_ID: '{{ yak_azure_virtualmachine_azure_client_id }}'
        AZURE_SECRET: '{{ yak_azure_virtualmachine_azure_secret }}'
        AZURE_TENANT: '{{ yak_azure_virtualmachine_azure_tenant }}'
  rescue:
    - fail:
        msg: 'Please ensure your AZURE credentials are valid.'

