# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
# Enabling SSD would need to be cast in a proper Ansible way once Microsoft
# add the feature during the VM creation. An issue is opened for that:
# https://github.com/ansible-collections/azure/issues/1356
- name: Enable ultra SSD
  delegate_to: localhost
  ansible.builtin.shell: |
    az vm deallocate -n {{ server_name }} -g {{ resource_group }}
    az vm update -n {{ server_name }} -g {{ resource_group }} --ultra-ssd-enabled true
    az vm start -n {{ server_name }} -g {{ resource_group }}
  when:
    - storage_devices.specifications.storage_account_type is defined
    - storage_devices.specifications.storage_account_type == 'UltraSSD_LRS'
