# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- include_tasks: get_vm_state.yml

- block:
  - include_tasks: create_{{ os_type }}.yml
  - include_tasks: post_config_{{ os_type }}.yml
  when: r_get_vm_state|json_query('vms[?state==`present` && name==`'+server_name+'`]')|length == 0

- when: r_get_vm_state|json_query('vms[?state==`present` && name==`'+server_name+'`]')|length > 0
  block:
    - fail:
        msg: "Cannot Deploy as the instance already exists."
  # always:
  #   - name: Update server state
  #     delegate_to: localhost
  #     yak.core.yak_inventory_update:
  #       server_name: "{{ target }}"
  #       server_state: stopped
  #     when: yak_inventory_type == "database"