# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
role_root_device_ebs_option: #https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_EbsBlockDevice.html
    volume_type: "{{ aws_root_disk_parameters.volume_type | default('gp3', true) }}"
    volume_size: "{{ aws_root_disk_parameters.volume_size | default(role_os_default_values[os_type|lower].root_device_ebs_default_volume_size) | default(role_os_default_values.default.root_device_ebs_default_volume_size) }}"
    encrypted: "{{ aws_root_disk_parameters.encrypted | default(true) }}"
    delete_on_termination: "{{ aws_root_disk_parameters.delete_on_termination | default(true) }}"

role_os_default_values:
    windows:
        root_device_ebs_default_volume_size: 50
    linux:
        root_device_ebs_default_volume_size: 20
    default:
        root_device_ebs_default_volume_size: 20

