# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Check target type
  tags: always
  hosts: localhost
  gather_facts: no
  vars:
    debug: true
  tasks:

    - shell: "ls -la /etc/ansible"

    - shell: "cat /etc/ansible/ansible.cfg"

    - shell: "ls -la /root/.ansible"

    - shell: "cat /root/.ansible/ansible.cfg"