# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Check target type
  tags: always
  hosts: "{{ target }}"
  gather_facts: no
  vars:
    debug: true
  tasks:

    - delegate_to: localhost
      shell: "cat /runner/project/ansible.cfg"

    - delegate_to: localhost
      shell: "env"