# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Check target type
  tags: always
  hosts: localhost
  gather_facts: no
  vars:
    debug: true
  tasks:

    - shell: "echo $ANSIBLE_ROLES_PATH"