# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Check target type
  tags: always
  hosts: "{{ target }}"
  gather_facts: no
  vars:
    debug: false
  tasks:

    - delegate_to: localhost
      ansible.builtin.assert:
        that:
          - target_type == 'server'
        msg: "This playbook can only run on 'server' target type. Current is '{{ target_type }}'."

- name: Deploy/update server
  tags: server
  hosts: "{{ target }}"
  gather_facts: no
  vars:
    debug: false
  tasks:

    - name: Update server state
      delegate_to: localhost
      yak.core.yak_inventory_update:
        server_name: "{{ target }}"
        server_state: starting
      when: yak_inventory_type == "database"

    - include_tasks: "deploy/{{ provider }}.yml"

- name: Apply server prerequisites
  tags: requirements
  hosts: "{{ target }}"
  vars:
    debug: false
  tasks:

    - include_role:
        name: yak.core.os_prerequisites
      vars:
        host_name: "{{ hostname }}"

    - include_role:
        name: yak.core.os_storage
      loop: "{{ yak_inventory_os_storages|default([]) }}"
      loop_control:
        loop_var: os_storage
