# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Start server
  hosts: "{{ target }}"
  gather_facts: no
  vars:
    debug: false
  tasks:

    - name: Update server state
      delegate_to: localhost
      yak.core.yak_inventory_update:
        server_name: "{{ target }}"
        server_state: starting
      when: yak_inventory_type == "database"

    - include_tasks: "start/{{ provider }}.yml"

    - name: Update server state
      delegate_to: localhost
      yak.core.yak_inventory_update:
        server_name: "{{ target }}"
        server_state: running
      when: yak_inventory_type == "database"
