# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Define hostname to {{ host_name }}
  become: yes
  ansible.builtin.hostname:
    name: "{{ host_name }}"

- name: Update /etc/hosts with ansible_fqdn
  become: yes
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ host_name }} {{ host_name }}.{{ domain_name }}"
    state: present

- name: Set timezone to {{ time_zone }}
  become: yes
  community.general.timezone:
    name: "{{ time_zone }}"

