# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Update cache and install packages
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    name:
      - 'lvm*'
      - xfsprogs
      - htop
      - iotop
