# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
debug: false
custom_tags: "{}"
role_storage_devices:
  specifications:
    storage_account_type: "{{ storage_devices.specifications.storage_account_type|default('StandardSSD_LRS') }}"

role_root_device_storage_account_type: "{{ root_device_storage_account_type|default('StandardSSD_LRS') }}"

role_dns:
  type: "{{ dns.type|default('none')}}"              # managed, custom, none
  dns_servers: "{{ dns.dns_servers|default(omit)}}"  # List/string | Which DNS servers should the NIC lookup.

yak_azure_virtualmachine_azure_subscription_id: "{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}"
yak_azure_virtualmachine_azure_client_id: "{{ lookup('env','AZURE_CLIENT_ID') }}"
yak_azure_virtualmachine_azure_secret: "{{ lookup('env','AZURE_SECRET') }}"
yak_azure_virtualmachine_azure_tenant: "{{ lookup('env','AZURE_TENANT') }}"

# Encryption at host for azure is enable if it is set to true at server or infra scope level.
encryption_at_host: '{{ infra_encryption_at_host|default(false) or server_encryption_at_host|default(false) }}'
