# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- ansible.builtin.include_role:
    name: yak.core.oci_compute
    tasks_from: check_credential.yml
  vars:
    yak_oci_compute_oci_ansible_auth_type: "{{ yak_artifact_provider_oci_ansible_auth_type }}"
    yak_oci_compute_oci_user_id: "{{ yak_artifact_provider_oci_user_id }}"
    yak_oci_compute_oci_user_fingerprint: "{{ yak_artifact_provider_oci_user_fingerprint }}"
    yak_oci_compute_oci_region: "{{ yak_artifact_provider_oci_region }}"
    yak_oci_compute_oci_tenancy: "{{ yak_artifact_provider_oci_tenancy }}"
    yak_oci_compute_oci_user_key_file: "{{ yak_artifact_provider_oci_user_key_file }}"

- name: Install python3-pip
  become: true
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install oci
  become: true
  ansible.builtin.pip:
    name: oci

- name: Create a directory if it does not exist
  become: true
  ansible.builtin.file:
    path: "~/.oci"
    state: directory
    mode: '0755'

- name: Ensure configuration file exists
  ansible.builtin.file:
    path: "~/.oci/config"
    state: touch
    mode: '0600'
  become: true

- name: Copy Key File
  become: true
  ansible.builtin.copy:
    src: "{{ yak_artifact_provider_oci_user_key_file }}"
    dest: "~/.oci/key"
    mode: '0600'

- name: Download artifact
  become: true
  oracle.oci.oci_object_storage_object:
    namespace_name: "{{ artifacts.variables.namespace_name }}"
    bucket_name: "{{ artifacts.variables.bucket_name }}"
    object_name: "{{ item }}"
    force: true
    dest: "{{ destination_path }}/{{ item }}"
    ## Authentication data
    auth_type: "{{ yak_artifact_provider_oci_ansible_auth_type }}"
    api_user: "{{ yak_artifact_provider_oci_user_id }}"
    api_user_fingerprint: "{{ yak_artifact_provider_oci_user_fingerprint }}"
    tenancy: "{{ yak_artifact_provider_oci_tenancy }}"
    region: "{{ yak_artifact_provider_oci_region }}"
    api_user_key_file: "~/.oci/key"
  loop: "{{ artifact_files }}"

- name: Remove Key File
  become: true
  ansible.builtin.file:
    path: "~/.oci/key"
    state: absent
...
