# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Create volume
  delegate_to: localhost
  oracle.oci.oci_blockstorage_volume:
    compartment_id: "{{ compartment_id }}"
    availability_domain: "{{ availability_domain }}"
    display_name: "{{ machine_name }}_disk_{{ item.drive_letter }}_{{ item.partition_label }}"
    size_in_gbs: "{{ item.size_gb|int }}"
    vpus_per_gb: "{{ role_storage_devices.oci_component_disk_parameters.vpus_per_gb }}"
    freeform_tags : "{{ {
                          'Name': 'disk_'+item.drive_letter+'_'+item.partition_label,
                          'Partition_label': item.partition_label,
                          'Drive_letter': item.drive_letter
                        }
                        | combine(custom_tags) }}"
  register: r_oci_blockstorage_volume_present
  loop: "{{ yak_inventory_os_storages }}"

- debug: var=r_oci_blockstorage_volume_present
  delegate_to: localhost
  when: debug | bool

- name: Get instances ID
  delegate_to: localhost
  oracle.oci.oci_compute_instance_facts:
    compartment_id: "{{ compartment_id }}"
    availability_domain: "{{ availability_domain }}"
    display_name: "{{ machine_name }}"
    lifecycle_state: RUNNING
  register: r_oci_compute_instance_facts
  failed_when: r_oci_compute_instance_facts.instances|length == 0

- debug: var=r_oci_compute_instance_facts
  delegate_to: localhost
  when: debug | bool

- name: Create volume attachment
  delegate_to: localhost
  oracle.oci.oci_compute_volume_attachment:
    compartment_id: "{{ compartment_id }}"
    type: iscsi
    instance_id: "{{ r_oci_compute_instance_facts.instances[0].id }}"
    volume_id: "{{ item.volume.id }}"
  loop: "{{ r_oci_blockstorage_volume_present.results }}"
  register: r_oci_blockstorage_volume_attachment

- debug: var=r_oci_blockstorage_volume_attachment
  delegate_to: localhost
  when: debug | bool

