- name: Set expiration period
  set_fact:
    sas_time_start: '{{ ansible_date_time.iso8601_micro }}'
    sas_time_expire: >-
      {{ ('%Y-%m-%dT%H:%M:%S'
        | strftime(ansible_date_time.epoch|int + 1200, utc=true))
        ~ (ansible_date_time.iso8601_micro | splitext)[1] }}

    
- name: Generate access signature
  delegate_to: localhost
  azure.azcollection.azure_rm_resource:
    resource_group: "{{ artifacts.variables.resource_group }}"
    method: POST
    url: "/subscriptions/{{ yak_artifact_provider_azure_subscription_id }}\
          /resourceGroups/{{ artifacts.variables.resource_group }}/providers/\
          Microsoft.Storage/storageAccounts/\
          {{ artifacts.variables.storage_account_name }}/ListServiceSas/"
    body:
      canonicalizedResource: '/blob/{{ artifacts.variables.storage_account_name }}/{{ artifacts.variables.container }}/{{ artifact_path }}'
      signedResource: b
      signedPermission: r
      signedStart: '{{ sas_time_start }}'
      signedExpiry: '{{ sas_time_expire }}'
  register: response_azure_sas
  environment:
    AZURE_SUBSCRIPTION_ID: "{{ yak_artifact_provider_azure_subscription_id }}"
    AZURE_CLIENT_ID: "{{ yak_artifact_provider_azure_client_id }}"
    AZURE_SECRET: "{{ yak_artifact_provider_azure_secret }}"
    AZURE_TENANT: "{{ yak_artifact_provider_azure_tenant }}"
