
- include_tasks: generate_sas_token.yml

- name: Copy blob
  become: true
  shell: >
    /usr/local/bin/azcopy cp
    "https://{{ artifacts.variables.storage_account_name }}.blob.core.windows.net/{{ artifacts.variables.container }}/{{ artifact_path }}?{{ response_azure_sas.response.serviceSasToken }}"
    "{{ destination_path }}/{{ artifact_path }}"
