# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- ansible.builtin.include_role:
    name: yak.core.azure_virtualmachine
    tasks_from: check_credential.yml
  vars:
    yak_azure_virtualmachine_azure_subscription_id: "{{ yak_artifact_provider_azure_subscription_id }}"
    yak_azure_virtualmachine_azure_client_id: "{{ yak_artifact_provider_azure_client_id }}"
    yak_azure_virtualmachine_azure_secret: "{{ yak_artifact_provider_azure_secret }}"
    yak_azure_virtualmachine_azure_tenant: "{{ yak_artifact_provider_azure_tenant }}"
    
- name: Download azcopy
  ansible.builtin.get_url:
    url: https://aka.ms/downloadazcopy-v10-linux
    dest: /tmp
    mode: '0740'
  register: r_get_url_azcopy

- debug: var=r_get_url_azcopy.dest
  when: debug|bool

- name: Unarchive azcopy
  ansible.builtin.unarchive:
    src: "{{ r_get_url_azcopy.dest }}"
    dest: /tmp
    remote_src: yes

- name: Install azcopy
  become: true
  ansible.builtin.copy:
    src: "{{ r_get_url_azcopy.dest[:-7] }}/azcopy"
    dest: /usr/local/bin/azcopy
    mode: '0755'
    remote_src: yes


- include_tasks: linux_blob_download.yml
  loop: "{{ artifact_files }}"
  loop_control:
    loop_var: artifact_path
