# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- ansible.builtin.include_role:
    name: yak.core.azure_virtualmachine
    tasks_from: check_credential.yml
  vars:
    yak_azure_virtualmachine_azure_subscription_id: "{{ yak_artifact_provider_azure_subscription_id }}"
    yak_azure_virtualmachine_azure_client_id: "{{ yak_artifact_provider_azure_client_id }}"
    yak_azure_virtualmachine_azure_secret: "{{ yak_artifact_provider_azure_secret }}"
    yak_azure_virtualmachine_azure_tenant: "{{ yak_artifact_provider_azure_tenant }}"

- name: Download azcopy
  ansible.builtin.win_get_url:
    url: https://aka.ms/downloadazcopy-v10-windows
    dest: C:\Users\Ansible\azcopy.zip
  register: r_get_url_azcopy

- debug: var=r_get_url_azcopy
  when: debug|bool

- name: Unzip azcopy
  ansible.builtin.win_unzip:
    src: C:\Users\Ansible\azcopy.zip
    dest: C:\Users\Ansible
    remote_src: yes

- name: Retrieve file path
  ansible.windows.win_powershell:
    script: |
      Get-ChildItem "C:\Users\Ansible\azcopy_windows_*\azcopy.exe" | %{$_.FullName}
  register: r_azcopy

- debug: var=r_azcopy
  when: debug|bool

- include_tasks: windows_blob_download.yml
  loop: "{{ artifact_files }}"
  loop_control:
    loop_var: artifact_path
