# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Role needs some variables
  ansible.builtin.assert:
    that: "{{ item }} is defined"
    fail_msg: "{{ item }} variable is undefined. Please, check instructions in the README.md file of the role."
    success_msg: "Variables properly set."
  loop: "{{ variables_to_check }}"

- name: Some artifacts providers need variables
  ansible.builtin.assert:
    that:
      - artifacts.variables is defined
    fail_msg: "Variables not properly set. Please, check instructions in the README.md file of the role."
    success_msg: "Variables variable properly set."
  when: artifacts.provider != 'yak_local_storage'

- name: Include pre tasks for OS {{ os_type }}
  include_tasks: "{{ os_type }}_pre.yml"

- name: Include tasks for OS {{ os_type }} with artifact provider {{ artifacts.provider }}
  include_tasks: "{{ artifacts.provider }}/{{ os_type }}.yml"

- name: Include post tasks for OS {{ os_type }}
  include_tasks: "{{ os_type }}_post.yml"
...
