# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- include_tasks: derive_volumes_need.yml
- include_tasks: define_linux_variable.yml


- name: Failing if finding a disk with old naming convention
  delegate_to: localhost
  azure.azcollection.azure_rm_manageddisk_info:
    name: "{{ machine_name }}_disk{{ item }}"
    resource_group: "{{ resource_group }}"
  register: r_azure_rm_manageddisk_info
  failed_when: r_azure_rm_manageddisk_info.ansible_info.azure_managed_disk | length > 0
  loop: "{{ query('sequence', 'start=1 end='+(number_of_devices)|string) }}"

- name: Create and attach the managed disk to VM
  delegate_to: localhost
  azure.azcollection.azure_rm_manageddisk:
    name: "{{ machine_name }}-disk{{ item }}"
    resource_group: "{{ resource_group }}"
    zone: "{{ zone_id|default(omit) }}"
    disk_size_gb: "{{ os_storage_disk_new_size }}"
    managed_by: "{{ machine_name }}"
    os_type: "{{ os_type }}"
    storage_account_type: "{{ yak_filesystem_configuration.managed_disk_type }}"
    attach_caching: "{{ yak_filesystem_configuration.os_disk_caching }}"
    tags: "{{ {'Name': 'disk'+item} | combine(custom_tags) }}"
  register: r_azure_rm_manageddisk
  loop: "{{ query('sequence', 'start=1 end='+(number_of_devices)|string) }}"

- debug: var=r_azure_rm_manageddisk
  delegate_to: localhost
  when: debug | bool
