# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Failing if finding a disk with old naming convention
  delegate_to: localhost
  azure.azcollection.azure_rm_manageddisk_info:
    name: "{{ machine_name }}_disk_{{ yak_filesystem_configuration.drive_letter }}_{{ yak_filesystem_configuration.partition_label }}"
    resource_group: "{{ resource_group }}"
  register: r_azure_rm_manageddisk_info
  failed_when: r_azure_rm_manageddisk_info.ansible_info.azure_managed_disk | length > 0

- name: Create and attach the managed disk to VM
  delegate_to: localhost
  azure.azcollection.azure_rm_manageddisk:
    name: "disk-{{ machine_name }}-{{ yak_filesystem_configuration.drive_letter }}-{{ yak_filesystem_configuration.partition_label }}"
    resource_group: "{{ resource_group }}"
    zone: "{{ zone_id|default(omit) }}"
    disk_size_gb: "{{ yak_filesystem_configuration.size_gb|int }}"
    managed_by: "{{ machine_name }}"
    os_type: "{{ os_type }}"
    storage_account_type: "{{ yak_filesystem_configuration.managed_disk_type }}"
    attach_caching: "{{ mapping_os_disk_caching[yak_filesystem_configuration.os_disk_caching] | default('read_write') }}"
    tags : >
      {{
        {
          'Name': 'disk-' + machine_name + '-' + yak_filesystem_configuration.drive_letter + '-' + yak_filesystem_configuration.partition_label,
          'Partition_label': yak_filesystem_configuration.partition_label,
          'Drive_letter': yak_filesystem_configuration.drive_letter
        }
        | combine(custom_tags)
      }}
  register: r_azure_rm_manageddisk

- debug: var=r_azure_rm_manageddisk
  delegate_to: localhost
  when: debug | bool


