# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
# IMPORTANT: On Azure, the only way to make a link between machine disks and
# their device mapping in the VM is by checking the value LUN number of the
# Azure VM and to match it with the path /dev/disk/azure/scsi1/lun{LUN number}
# in the Linux VM.

- name: Get facts by name
  delegate_to: localhost
  azure_rm_virtualmachine_info:
    name: "{{ machine_name }}"
    resource_group: "{{ resource_group }}"
  register: r_azure_rm_virtualmachine_info

- set_fact:
    azure_storage_disks_name: []
    pvs_list: []

- set_fact:
    azure_storage_disks_name: '{{ azure_storage_disks_name + [item.state.name] }}'
  loop: '{{ r_azure_rm_manageddisk.results }}'

- when: 
  - item.name in azure_storage_disks_name
  - r_azure_rm_virtualmachine_info.vms[0].name == machine_name
  name: Extract LUN for each managed disk
  set_fact:
    pvs_list: "{{ pvs_list + [ '/dev/disk/azure/scsi1/lun' + item.lun|string ] }}"
  loop: "{{ r_azure_rm_virtualmachine_info.vms[0].data_disks }}"

- debug: var=pvs_list
  when: debug | bool

- name: Create a volume group
  become: yes
  lvg:
    vg: "{{ sanitized_mount_point_name }}"
    pvs: "{{ pvs_list }}"
