# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
- name: Gather information about instance
  delegate_to: localhost
  community.aws.ec2_instance_info:
    region: "{{ region_id }}"
    filters:
      "tag:Name": "{{ machine_name }}"
      instance-state-name: [ "pending", "running", "shutting-down", "stopping", "stopped" ]
  register: r_ec2_instance_info

- debug: var=r_ec2_instance_info
  when: debug | bool

- name: Get volume(s) info from EC2 Instance
  delegate_to: localhost
  amazon.aws.ec2_vol_info:
    region: "{{ region_id }}"
    filters:
      attachment.instance-id: "{{ r_ec2_instance_info.instances[0].instance_id }}"
      "tag:yak_mount_point": "{{ yak_filesystem_configuration.mount_point }}"
  register: r_attached_volumes

- debug: var=r_attached_volumes
  when: debug | bool

- include_tasks: "volumes_aws_derive_pv.yml"

- debug: var=r_derive_pv_list
  when: debug | bool

- name: Create a volume group
  become: yes
  lvg:
    vg: "{{ sanitized_mount_point_name }}"
    pvs: "{{ r_derive_pv_list.pv_list }}"


